name: Run FD Experiment

on:
  workflow_dispatch:
  push:
    paths:
      - 'finite_diff_run.py'
      - 'requirements.txt'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run experiment
        run: python finite_diff_run.py
      - name: Archive outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/**
          if-no-files-found: error
